### ISSUE TITLE
Improve logging on ingress status update failure

### ISSUE THREAD

**Issue by danbreed** [sky-uk/feed#179]
Should we consider logging the error here? At present we only log that it has failed but not the reason why.

https://github.com/sky-uk/feed/blob/288c881ee722f1a3547bdb162ec62eb9f6f8b824/k8s/status/status.go#L40-L42

**Comment by peterbale** [comment]
I've had a look at the errors received from k8s when a call fails and it's very hard to dedupe due the error including a lot of data specific to the ingress. I have a raised a PR which created a multierror and then returns that to the controller to log out. As for a debug log, I think if we did this it would be too late for us to catch realtime issues effectively.
