### ISSUE TITLE
Improve feed tests

### ISSUE THREAD

**Issue by supreethrao** [sky-uk/feed#189]
- [ ] None of the tests we have actually starts up nginx. So, if we make a mistake in the nginx.tmpl, it won't be identified till it's released
- [ ] There needs to some performance test which is run as part of the feed build/release process so that any performance impacting changes can be stopped before it's released.

**Comment by domleb** [comment]
This is related to https://github.com/sky-uk/core-infrastructure/issues/2833

The current plan is to treat feed as a 3rd party (open source) component and therefore do our nft as part of the prod pipeline that uses the released artifact.  We could also test the config in stubbed-functional.

**Comment by supreethrao** [comment]
Thanks @domleb but do we think it's ok to leave it thus far (to components using this) to identify any performance degrading. 

I appreciate that it might be difficult to create a one size fits all NFT but it might help if we have some reference script which identifies any degrade of say response time compared to the previous release. The components which use feed-ingress can do their own specific performance tests using load and data which is comparable to the component's need.

**Comment by domleb** [comment]
I'm sure it would be possible to add some basic NFT to the feed project but I guess it would have to run locally right?  We couldn't run it in a cloud account for an open source repo.

**Comment by jsravn** [comment]
You couldn't run load tests, but you can run feed on travis via minikube to test the entire integration w/ nginx. https://github.com/lightbend/helm-charts/blob/master/scripts/setup-minikube-for-linux.sh is an example of how to do it.

**Comment by supreethrao** [comment]
Thanks @domleb @jsravn If we could start up nginx on a minikube, could we not have another light-weight docker container deployed on minikube, just injecting load for a short duration ? It could be as simple as `ab` 

But it would be great to atleast test the integration. Thanks a lot for the example.

**Comment by jsravn** [comment]
It could be something very simple yeah, but you're likely to get in trouble with Travis, or seriously throttled, if you started running long-lived load tests. Also travis slaves tend to be severely underpowered so it wouldn't be particularly accurate. Best to run those on your own infra.

**Comment by supreethrao** [comment]
Makes sense. Thanks @jsravn

**Comment by peterbale** [comment]
Closing as this issue is stale
