### ISSUE TITLE
GitLeaks - Private Key

### ISSUE THREAD

**Issue by SkyDevSecOps-SCMA** [sky-uk/feed#258]
Locations:<br><ul><li><a href='https://github.com/sky-uk/feed/blob/941d549e7fe95ef65ef822e0268ca96c519a9a7f/k8s/client_test.go#L491-L517'>k8s/client_test.go</a></li></ul><br> In case of questions please visit our FAQ page here: https://skyglobal.sharepoint.com/sites/GroupCyberSecurity10/SitePages/Software-Security.aspx

**Comment by peterbale** [comment]
This private key is part of a functional test in the project and has nothing to do with the delivered service once built, so this is not sensitive information.
